name: Test

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Flutter
        uses: actions/cache@v2
        env:
          cache-name: cache-flutter
        with:
          # Flutter cache files are stored in `~/.flutter` on Linux/macOS
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install flutter
        uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '2.2.0'
          channel: 'stable'

      - name: Get dependencies
        run: speech_to_text/flutter pub get

      - name: Run tests
        run: speech_to_text/flutter test
