name: speech_to_text_windows_example
description: Example app for the Windows speech-to-text plugin
version: 1.0.0+1
publish_to: none  # This fixes the path dependency warning

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_windows:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true