name: Test

on:
  push:
    branches:
    - main

jobs:
  test:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter
        uses: actions/cache@v3
        env:
          cache-name: cache-flutter
        with:
          # Flutter cache files are stored in `~/.flutter` on Linux/macOS
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: Get platform interface dependencies
        run: flutter pub get
        working-directory: speech_to_text_platform_interface

      - name: Run platform interface tests
        run: flutter test
        working-directory: speech_to_text_platform_interface

      - name: Get plugin dependencies
        run: flutter pub get
        working-directory: speech_to_text

      - name: Run plugin tests
        run: flutter test
        working-directory: speech_to_text
